ARG PORT=443
FROM cypress/browser:latest

# Install Python and dependencies
RUN apt-get update && apt-get install -y python3 python3-pip

# Set up PATH for user-installed packages
ENV PATH /home/root/.local/bin:${PATH}

# Install Python dependencies
COPY requirements.txt .
RUN pip install packaging && pip install -r requirements.txt

# Copy application files
COPY . .

# Start the app
CMD uvicorn main:app --host 0.0.0.0 --port $PORT
